services:
  create-schema:
    build:
      context: ./db
      dockerfile: Dockerfile.create_schema

    container_name: tf-create-schema

    env_file:
      - .env.schemas

    networks:
      - app-network
      
    volumes:
      - ./db/schemas.conf:/app/schemas.conf:ro

    stdin_open: true
    tty: true

    restart: "no"

networks:
  app-network:
    driver: bridge
