services:
  create-schema:
    build:
      context: ./db
      dockerfile: Dockerfile.create_schema

    container_name: tf-create-schema

    env_file:
      - .env.schemas
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_PASSWORD}

    networks:
      - app-network
      
    volumes:
      - ./db/schemas.conf:/app/schemas.conf:ro

    stdin_open: true
    tty: true

    restart: "no"

networks:
  app-network:
    driver: bridge